/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Counter__factory } from './Counter__factory.js';
export { EduAccessControl__factory } from './EduAccessControl__factory.js';